theme: jekyll-theme-minimal
layout: page
title: Griffin's Projects and small data science showcase
description: This site is my front-facing project showcase that highlights small and for-fun projects I have done over time!
